apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tomcat8-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcat-app
  template:
    metadata:
      labels:
        app: tomcat-app
    spec:
      containers:
      - name: tomcat8-pod
        image: brunojose1977/tomcat8
